version: '2'
services: 
    php:
        container_name: project_app
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on:
            - database

    # Database Server
    database:
        container_name: project_db
        platform: linux/x86_64
        image: mysql:8.0
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 3306:3306
# volumes:
#   db-data : ~